Select
	Customer_ID,
	Gender,
	Age,
	Married,
	State,
	Number_of_Referrals,
	Tenure_in_Months,
	ISNULL(Value_Deal, 'None') As Value_Deal,
	Phone_Service,
	ISNULL(Multiple_Lines, 'No') As Multiple_Lines,
	Internet_Service,
	ISNULL(Internet_Type, 'None') As Internet_Type,
	ISNULL(Online_Security, 'No') As Online_Security,
	ISNULL(Online_Backup, 'None') As Online_Backup,
	ISNULL(Device_Protection_Plan, 'No') As Device_Protection_Plan,
	ISNULL(Premium_Support, 'None') As Premium_Support,
	ISNULL(Streaming_TV, 'No') As Streaming_TV,
	ISNULL(Streaming_Movies, 'None') As Streaming_Movies,
	ISNULL(Streaming_Music, 'No') As Streaming_Music,
	ISNULL(Unlimited_Data, 'No') As Unlimited_Data,
	Contract,
	Paperless_Billing,
	Payment_Method,
	Monthly_Charge,
	Total_Charges,
	Total_Refunds,
	Total_Extra_Data_Charges,
	Total_Long_Distance_Charges,
	Total_Revenue,
	Customer_Status,
	ISNULL(Churn_Category, 'No') As Churn_Category,
	ISNULL(Churn_Reason, 'No') As Churn_Reason
Into [db_Churn].[dbo].[prod_Churn]
from [db_Churn].[dbo].[stg_Churn];
